//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MajorMinorNumber.ConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MajorMinorNumber.ConsoleApp.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both numbers are the same..
        /// </summary>
        public static string BOTH_NUMBERS_ARE_SAME {
            get {
                return ResourceManager.GetString("BOTH_NUMBERS_ARE_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 2 numbers separeted with &apos;,&apos; (comma) or &apos;q&apos; to quit..
        /// </summary>
        public static string INITIAL_CONSOLE_MESSAGE {
            get {
                return ResourceManager.GetString("INITIAL_CONSOLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is bigger than 1000. Number Max 1000..
        /// </summary>
        public static string IS_BIGGER_THAN_1000 {
            get {
                return ResourceManager.GetString("IS_BIGGER_THAN_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is smaller than -1000. Number Min -1000..
        /// </summary>
        public static string IS_SMALLER_THAN_MINUS_1000 {
            get {
                return ResourceManager.GetString("IS_SMALLER_THAN_MINUS_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the biggest number..
        /// </summary>
        public static string IS_THE_BIGGEST_NUMBER {
            get {
                return ResourceManager.GetString("IS_THE_BIGGEST_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has less than 2 numbers..
        /// </summary>
        public static string IT_HAS_LESS_THAN_2_NUMBERS {
            get {
                return ResourceManager.GetString("IT_HAS_LESS_THAN_2_NUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has more than 2 numbers..
        /// </summary>
        public static string IT_HAS_MORE_THAN_2_NUMBERS {
            get {
                return ResourceManager.GetString("IT_HAS_MORE_THAN_2_NUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListNumbers is empty..
        /// </summary>
        public static string LISTNUMBERS_IS_EMPTY {
            get {
                return ResourceManager.GetString("LISTNUMBERS_IS_EMPTY", resourceCulture);
            }
        }
    }
}
