//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgeMajority.ConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgeMajority.ConsoleApp.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age can&apos;t be less than 0.
        /// </summary>
        public static string AGE_CANT_BE_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("AGE_CANT_BE_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age can&apos;t be more than 200.
        /// </summary>
        public static string AGE_CANT_BE_MORE_THAN_200 {
            get {
                return ResourceManager.GetString("AGE_CANT_BE_MORE_THAN_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a age or &apos;q&apos; to quit.
        /// </summary>
        public static string ENTER_AGE_OR_PRESS_Q_QUIT {
            get {
                return ResourceManager.GetString("ENTER_AGE_OR_PRESS_Q_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Format Incorrect, digit only numbers.
        /// </summary>
        public static string INPUT_FORMAT_INCORRECT {
            get {
                return ResourceManager.GetString("INPUT_FORMAT_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Format Incorrect, digit only numbers (BASE).
        /// </summary>
        public static string INPUT_FORMAT_INCORRECT_BASE {
            get {
                return ResourceManager.GetString("INPUT_FORMAT_INCORRECT_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is already majority Age.
        /// </summary>
        public static string IS_ALREADY_MAJORITY_AGE {
            get {
                return ResourceManager.GetString("IS_ALREADY_MAJORITY_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is still minor Age.
        /// </summary>
        public static string IS_STILL_MINOR_AGE {
            get {
                return ResourceManager.GetString("IS_STILL_MINOR_AGE", resourceCulture);
            }
        }
    }
}
